FUNC LABEL 0
    MOV STK A VAL 1
    MOV STK B VAL 2
    MOV STK C VAL 3
    MOV STK D VAL 1
    MOV STK E VAL 2
    MOV STK F VAL 3
    MOV STK G VAL 1
    MOV STK H VAL 2
    MOV STK I VAL 3
    MOV STK J VAL 1
    MOV STK K VAL 2
    MOV STK L VAL 3
    MOV STK M VAL 1
    MOV STK N VAL 2
    MOV STK O VAL 3
    MOV STK P VAL 3
    MOV STK Q VAL 1
    MOV STK R VAL 2
    MOV STK S VAL 3
    MOV STK T VAL 3
    MOV STK U VAL 1
    MOV STK V VAL 2
    MOV STK W VAL 3
    MOV STK X VAL 1
    MOV STK Y VAL 2
    MOV STK Z VAL 3
    MOV STK a VAL 1
    MOV STK b VAL 28
    PRINT STK b
    RET
